### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by jcwalker**
Initial PR

---
This change is [Reviewable](https://reviewable.io/reviews/jcwalker/processmitigationdsc/1)

### CODE REVIEW

**Comment by regedit32** [comment]
Reviewed 10 of 10 files at r1.
Review status: 9 of 11 files reviewed at latest revision, all discussions resolved.

---

*[DSCResource.Tests, line 1 at r1](https://beta.reviewable.io/reviews/jcwalker/processmitigationdsc/1#-L9L0k2y6nhwKgmfn-cb:-L9L0k2y6nhwKgmfn-cc:bmo296e) ([raw file](https://github.com/jcwalker/processmitigationdsc/blob/a673415bd567e0011ab948e0c49564aed4674ccb/DSCResource.Tests#L1)):*
> ```
> Subproject commit e7b3589bfba4c80e131ea6baf4f9f712336b6390
> ```

should be excluded from the repo

---

*[ProcessMitigationDsc.psd1, line 15 at r1](https://beta.reviewable.io/reviews/jcwalker/processmitigationdsc/1#-L9KzjEUBK5-01iEumXo:-L9KzjEUBK5-01iEumXp:b-6upm56) ([raw file](https://github.com/jcwalker/processmitigationdsc/blob/a673415bd567e0011ab948e0c49564aed4674ccb/ProcessMitigationDsc.psd1#L15)):*
> ```PowerShell
> 
>     # Version number of this module.
>     ModuleVersion     = '1.0'
> ```

Standard version scheme for DSC modules seems to be x.x.x.x

---

*[DSCResources/ProcessMitigation/ProcessMitigation.psm1, line 1 at r1](https://beta.reviewable.io/reviews/jcwalker/processmitigationdsc/1#-L9KzwvCEbIxRhaIwCkL:-L9KzwvCEbIxRhaIwCkM:bq2crc4) ([raw file](https://github.com/jcwalker/processmitigationdsc/blob/a673415bd567e0011ab948e0c49564aed4674ccb/DSCResources/ProcessMitigation/ProcessMitigation.psm1#L1)):*
> ```PowerShell
> function Get-TargetResource
> ```

should have comment based help for all functions

---

*[Tests/Unit/ProcessMitigation.tests.ps1, line 145 at r1](https://beta.reviewable.io/reviews/jcwalker/processmitigationdsc/1#-L9L0PhAE9tEo7LNEe_Q:-L9L0PhBBKF4AAO1buUe:b-jcwear) ([raw file](https://github.com/jcwalker/processmitigationdsc/blob/a673415bd567e0011ab948e0c49564aed4674ccb/Tests/Unit/ProcessMitigation.tests.ps1#L145)):*
> ```
> is
> ```
typo

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/jcwalker/processmitigationdsc/1)*

**Review by jcwalker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/jcwalker/windowsdefenderdsc/1)* status: 0 of 15 files reviewed, 4 unresolved discussions (waiting on @regedit32)

___
*[DSCResources/ProcessMitigation/ProcessMitigation.psm1, line 1 at r1](https://reviewable.io/reviews/jcwalker/windowsdefenderdsc/1#-L9KzwvCEbIxRhaIwCkL:-LKNXad62K5Z2_YuJGxa:b-896fix) ([raw file](https://github.com/jcwalker/windowsdefenderdsc/blob/a673415bd567e0011ab948e0c49564aed4674ccb/DSCResources/ProcessMitigation/ProcessMitigation.psm1#L1)):*
<details><summary><i>Previously, regedit32 (Reggie Gibson) wrote…</i></summary><blockquote>

should have comment based help for all functions
</blockquote></details>

Done.
___
*[Tests/Unit/ProcessMitigation.tests.ps1, line 145 at r1](https://reviewable.io/reviews/jcwalker/windowsdefenderdsc/1#-L9L0PhAE9tEo7LNEe_Q:-LKNYFRr60_svjNF1SnF:b-896fix) ([raw file](https://github.com/jcwalker/windowsdefenderdsc/blob/a673415bd567e0011ab948e0c49564aed4674ccb/Tests/Unit/ProcessMitigation.tests.ps1#L145)):*
<details><summary><i>Previously, regedit32 (Reggie Gibson) wrote…</i></summary><blockquote>

> ```
> is
> ```
typo
</blockquote></details>

Done.
___
*[DSCResource.Tests, line 1 at r1](https://reviewable.io/reviews/jcwalker/windowsdefenderdsc/1#-L9L0k2y6nhwKgmfn-cb:-LKNYHbuAz0vG9CITfzJ:b-896fix) ([raw file](https://github.com/jcwalker/windowsdefenderdsc/blob/a673415bd567e0011ab948e0c49564aed4674ccb/DSCResource.Tests#L1)):*
<details><summary><i>Previously, regedit32 (Reggie Gibson) wrote…</i></summary><blockquote>

should be excluded from the repo
</blockquote></details>

Done.
___
*[ProcessMitigationDsc.psd1, line 15 at r1](https://reviewable.io/reviews/jcwalker/windowsdefenderdsc/1#-L9KzjEUBK5-01iEumXo:-LKNYM983VZgbzmPj8BH:b-896fix) ([raw file](https://github.com/jcwalker/windowsdefenderdsc/blob/a673415bd567e0011ab948e0c49564aed4674ccb/ProcessMitigationDsc.psd1#L15)):*
<details><summary><i>Previously, regedit32 (Reggie Gibson) wrote…</i></summary><blockquote>

Standard version scheme for DSC modules seems to be x.x.x.x
</blockquote></details>

Done.

**Review by ldillonel — COMMENTED** [review]
> Reviewed 8 of 15 files at r3, 1 of 3 files at r4, 1 of 3 files at r5, 7 of 8 files at r6.
> *[Reviewable](https://reviewable.io/reviews/jcwalker/windowsdefenderdsc/1)* status: all files reviewed, 4 unresolved discussions (waiting on @regedit32)

**Review by nehrua — COMMENTED** [review]
> Reviewed 3 of 15 files at r3, 1 of 3 files at r5, 2 of 8 files at r6.
> *[Reviewable](https://reviewable.io/reviews/jcwalker/windowsdefenderdsc/1)* status: all files reviewed, 5 unresolved discussions (waiting on @regedit32 and @jcwalker)

___
*[appveyor.yml, line 39 at r6](https://reviewable.io/reviews/jcwalker/windowsdefenderdsc/1#-LKNh-B0BdWXM75pMzQB:-LKNh-B0BdWXM75pMzQC:b-1gpi5w) ([raw file](https://github.com/jcwalker/windowsdefenderdsc/blob/6e72f6f507500df456be5984e2c24116b21da1e3/appveyor.yml#L39)):*
> ```YAML
> deploy_script: 
> 
>   - ps: |
> ```

It appears a tab is missing here, as it doesn't align with the rest of the formatting within the file.

**Review by jcwalker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/jcwalker/windowsdefenderdsc/1)* status: 13 of 15 files reviewed, 5 unresolved discussions (waiting on @ldillonel, @nehrua, and @regedit32)

___
*[appveyor.yml, line 39 at r6](https://reviewable.io/reviews/jcwalker/windowsdefenderdsc/1#-LKNh-B0BdWXM75pMzQB:-LKOL9XU6A0yB3GKXkIC:bbt9pdr) ([raw file](https://github.com/jcwalker/windowsdefenderdsc/blob/6e72f6f507500df456be5984e2c24116b21da1e3/appveyor.yml#L39)):*
<details><summary><i>Previously, nehrua (Nehru Ali) wrote…</i></summary><blockquote>

It appears a tab is missing here, as it doesn't align with the rest of the formatting within the file.
</blockquote></details>

Good catch
Done.

**Review by nehrua — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/jcwalker/windowsdefenderdsc/1)* status: 12 of 15 files reviewed, 6 unresolved discussions (waiting on @ldillonel, @nehrua, @regedit32, and @jcwalker)

___
*[DSCResources/ProcessMitigation/ProcessMitigation.psm1, line 238 at r7](https://reviewable.io/reviews/jcwalker/windowsdefenderdsc/1#-LKOPc0YD0gkoqqStuth:-LKOPXYa9QBRykIw96t9:b5xk12y) ([raw file](https://github.com/jcwalker/windowsdefenderdsc/blob/d27d69f100822fa4b3806a3fca723003bcacde11/DSCResources/ProcessMitigation/ProcessMitigation.psm1#L238)):*
> ```PowerShell
>     param ()
>     
>     Import-Module -Name ProcessMitigations -Verbose:0
> ```

There appears to be a dependency on this module (ProcessMitigations) that must be met before a config can be applied.  Should this be addressed as a required module in the manifest?

**Review by jcwalker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/jcwalker/windowsdefenderdsc/1)* status: 12 of 15 files reviewed, 6 unresolved discussions (waiting on @ldillonel, @nehrua, @regedit32, and @jcwalker)

___
*[DSCResources/ProcessMitigation/ProcessMitigation.psm1, line 238 at r7](https://reviewable.io/reviews/jcwalker/windowsdefenderdsc/1#-LKOPc0YD0gkoqqStuth:-LKRcPNA7giNNGM_Mwye:bky6ms6) ([raw file](https://github.com/jcwalker/windowsdefenderdsc/blob/d27d69f100822fa4b3806a3fca723003bcacde11/DSCResources/ProcessMitigation/ProcessMitigation.psm1#L238)):*
<details><summary><i>Previously, nehrua (Nehru Ali) wrote…</i></summary><blockquote>

There appears to be a dependency on this module (ProcessMitigations) that must be met before a config can be applied.  Should this be addressed as a required module in the manifest?
</blockquote></details>

The RequiredModules in the manifest doesn't really work with a DSC resource.  I looked in other DSC resource that are in the DSC resource kit and they have RequiredModules removed from the manifest.  xWebAdministration uses a helper function "Assert-Module" that checks for the WebAdministartion module and then throw a terminating error.  The way the code behaves now, the error explains what is missing and it's not a terminating error so following resources will run.  I'm not sure if there is a benefit to creating an Assert-Module function in this case but I'm open for suggestions.

**Review by chasewilson — COMMENTED** [review]
> Reviewed 1 of 2 files at r7, 2 of 2 files at r8.
> *[Reviewable](https://reviewable.io/reviews/jcwalker/windowsdefenderdsc/1)* status: all files reviewed, 7 unresolved discussions (waiting on @regedit32, @nehrua, and @jcwalker)

___
*[DSCResources/ProcessMitigation/ProcessMitigation.psm1, line 78 at r8](https://reviewable.io/reviews/jcwalker/windowsdefenderdsc/1#-LKTMAF118WUR6E8TgsB:-LKTMAF2BXHZsxholpAc:b-9of0ma) ([raw file](https://github.com/jcwalker/windowsdefenderdsc/blob/6ad0c7053d1a8a25aa4b179fa9d482df3897f74d/DSCResources/ProcessMitigation/ProcessMitigation.psm1#L78)):*
> ```
>     $enableResults  = Get-ProcessMitgationResult -RawResult $results -ResultType Enable
>     $disableResults = Get-ProcessMitgationResult -RawResult $results -ResultType Disable
>     $defaultResults = Get-ProcessMitgationResult -RawResult $results -ResultType Default
> ```
You are going to hate me for this part, but wouldn't it be better to make the function return an object with those three different types rather than run the function threee times?

**Comment by jcwalker** [comment]
___
*[DSCResources/ProcessMitigation/ProcessMitigation.psm1, line 78 at r8](https://reviewable.io/reviews/jcwalker/windowsdefenderdsc/1#-LKTMAF118WUR6E8TgsB:-LKWYH7d3ZcMtDZALoPB:bt43ma6) ([raw file](https://github.com/jcwalker/windowsdefenderdsc/blob/6ad0c7053d1a8a25aa4b179fa9d482df3897f74d/DSCResources/ProcessMitigation/ProcessMitigation.psm1#L78)):*
<details><summary><i>Previously, chasewilson (Chase Wilson) wrote…</i></summary><blockquote>

> ```
>     $enableResults  = Get-ProcessMitgationResult -RawResult $results -ResultType Enable
>     $disableResults = Get-ProcessMitgationResult -RawResult $results -ResultType Disable
>     $defaultResults = Get-ProcessMitgationResult -RawResult $results -ResultType Default
> ```
You are going to hate me for this part, but wouldn't it be better to make the function return an object with those three different types rather than run the function threee times?
</blockquote></details>

You can't use my own criticism on me.

**Comment by jcwalker** [comment]
___
*[DSCResources/ProcessMitigation/ProcessMitigation.psm1, line 78 at r8](https://reviewable.io/reviews/jcwalker/windowsdefenderdsc/1#-LKTMAF118WUR6E8TgsB:-LKWuaOtCe4ScrG-PtSV:b-896fix) ([raw file](https://github.com/jcwalker/windowsdefenderdsc/blob/6ad0c7053d1a8a25aa4b179fa9d482df3897f74d/DSCResources/ProcessMitigation/ProcessMitigation.psm1#L78)):*
<details><summary><i>Previously, jcwalker (Jason Walker) wrote…</i></summary><blockquote>

You can't use my own criticism on me. 
</blockquote></details>

Done.

**Review by chasewilson — COMMENTED** [review]
:lgtm:

> Reviewed 4 of 4 files at r9.
> *[Reviewable](https://reviewable.io/reviews/jcwalker/windowsdefenderdsc/1#-:-LKX7h-6DA9qxc6k9S31:bnfp4nl)* status: all files reviewed, 6 unresolved discussions (waiting on @regedit32 and @nehrua)

**Pull request merged**
